### ISSUE TITLE
Task List for moving QuaggaJS to getUserBarcode

### ISSUE THREAD

**Issue by kristate** [NeraiCorp/getUserBarcode#1]
@serratus has gone MIA and this fork aims to bring more people and patches around the QuaggaJS project together.

**TODO**
- [ ] Change namespace from Quagga to getUserBarcode
- [ ] Move over Example Site
- [x] Update Bower Registery
- [x] Update NPM Registery

Please let me know of any other task items as appropriate. Thank-you.

**Comment by kristate** [comment]
Bower Updated:

```
Package getuserbarcode registered successfully!
All valid semver tags on git://github.com/NeraiCorp/getUserBarcode.git will be available as versions.
To publish a new version, just release a valid semver tag.
```

**Comment by kristate** [comment]
NPM Updated: https://www.npmjs.com/package/getuserbarcode

**Comment by serratus** [comment]
@kristate As mentioned in https://github.com/serratus/quaggaJS/issues/300 I would like to offer you to become a maintainer of Quagga

**Comment by backspace** [comment]
Why not transfer ownership as @TomasHubelbauer suggests [here](https://github.com/serratus/quaggaJS/issues/300#issuecomment-393551741)?
